### ISSUE TITLE
Classification by power requirements

### ISSUE THREAD

**Issue by evrial** [awesome-selfhosted/awesome-selfhosted-data#601]
I know that may be a lot of work but bloatware and software growing in size and power consumption is disturbing when you selfhosting on lower power devices like Raspberry, so ideally I wish to classify like this: cgit: 10, forgejo: 9, GitLab: 1, or low/med/high. Or maybe sort them in ascending order from lighweight, because alphabetic isn't helpful and I don't care about authors naming fantasy. And honestly I'd completely remove a-like Gitlab because that's anti-selfhosting as it gets.

Also I'd wish to express that you @nodiscc had perfectly social single repo where more than 1000 real people contributed and 171K stars and split into 3 repos with dumb bot commits made that perfectly anti-social repos and ugly pattern. The list was made by the people for the people, not by bots from some _smart_ dataset because parsing markdown is hard. You could go further and make a fucking CSV files.

**Comment by nodiscc** [comment]
> bloatware and software growing in size and power consumption is disturbing when you selfhosting on lower power devices like Raspberry

I share this concern, even on more powerful hardware, power efficiency should be considered when evaluating software for a particular task.

> so ideally I wish to classify like this: cgit: 10, forgejo: 9, GitLab: 1

cgit cannot be compared to forgejo/gitlab because the feature set is very different. If you need a simple Git web interface go for cgit, if you need issue tracking/code reviews/CI/whatever, evaluate a full forge, and consider all aspects (feature set, maintenance level, power efficiency, UX, ...).

In the end, critical thinking should be exercised when choosing software, and this is out of scope for this list (teaching people how to pick software for a particular task - if you can find or write articles about this process however that would be interesting). https://www.bestpractices.dev/en/projects covers some of these aspects, but not all. Rating software in this way is extremely subjective, and we're not going to introduce subjective "quality" ratings in the list beyond those we currently have (maintained, working, documented, FOSS), this has been debated countless times (search for `quality` in issues). What's a proper unit for power efficiency in software? kWh/byte processed? :thinking: Again if you can link to state-of-the art research on this subject it would be appreciated.

> Also I'd wish to express that you @nodiscc had perfectly social single repo where more than 1000 real people contributed and 171K stars and split into 3 repos with dumb bot commits made that perfectly anti-social repos and ugly pattern. The list was made by the people for the people, not by bots from some smart dataset because parsing markdown is hard

I invite you to do a bit of reading in the 9 years of project history/issues - displaying more information, checking "liveness" of projects, checking dead links, having the ability to put a project under multiple categories, checking syntax, gathering and updating data and other *extremely* boring tasks while keeping the list readable, has always been the goal. The recommended way to use the list is through https://awesome-selfhosted.net/, you can use the original markdown list which is still there, the dumb bot is just there to do dumb work (but maybe you'd like to take his position?).

The goal is not to be a "social" place (even if we get along nicely), or to collect github stars, but to be a useful resource. I don't get why this frustrates you. The only place where contributions/interactions happen is this one (`awesome-selfhosted-data`), the others are just auto-generated stuff.

> You could go further and make a fucking CSV files.

Don't tempt me

Have a nice day

**Comment by evrial** [comment]
Excuse my grumpy tone, your time and efforts are very appreciated. 
> What's a proper unit for power efficiency in software? kWh/byte processed? 🤔
Not an NP complete decision problem. We will discriminate anyway in terms of features. You could compute Pi number to 10 digits or infinitely, that's opposite dimensions in terms of power consumption. Or running Immich gallery with machine learning or without. But I think improvements in that regard are possible because we can tell what can run on 6.4W CPU and what can't

**Comment by nodiscc** [comment]
> Excuse my grumpy tone

No problem mate

> improvements in that regard are possible because we can tell what can run on 6.4W CPU and what can't

I agree, hardware requirements should be part of the basic documentation for any serious project. Even then, as you noted, actual requirements can still vary wildly depending on the number of concurrent users, what features are actually used or not, etc. so it can get complex really quick, and there is simply not enough room on the website, or workforce here to get into such a task.

The best course of action, in my opinion, is to get in touch with maintainers of projects you _did_ try/benchmark and propose an update to their docs to mention how well it performs on hardware x/y/z. For example it is obvious that [this](https://jellyfin.org/docs/general/administration/hardware-selection/) will not run very well on an arm development board.

**Comment by evrial** [comment]
I actually talked with Jellyfin devs and Immich dev about how can that be documented better. Because for them SBC isn't first class device, but if you don't need transcoding and able not to use web UI, they are plenty of power and able to stream 120 MBps 12 bit HDR movies. Same for Immich, without ML it is smooth. But I spent many hours before to find out all moving parts.

**Comment by nodiscc** [comment]
> they are plenty of power and able to stream 120 MBps 12 bit HDR movies. Same for Immich, without ML it is smooth

_This_ is valuable information (which doesn't belong on the list though), a number on a scale of 1 to 10 is not, is my point.

> But I spent many hours before to find out all moving parts.

No way around it.
