### ISSUE TITLE
Removed reciphpes! although still active (stable/mature)

### ISSUE THREAD

**Issue by nanawel** [awesome-selfhosted/awesome-selfhosted-data#819]
Hi,

I've noticed that [one of my projects](https://github.com/nanawel/reciphpes) has been removed from the list.
It's not been updated in 2 years but it's mainly because it is stable and feature-complete.

The original PR is there: https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3258

Is it possible to restore it? I didn't get any notice about removal :confused: 

Regards

**Comment by nodiscc** [comment]
It was removed [here](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/410) because third-party dependencies were not kept up-to-date and have security vulnerabilities. I suggest setting up an automatic dependency scanner such as [trivy](https://github.com/aquasecurity/trivy). When these issues are addressed you should create a new release and wait for the initial delay of 4 months after the first release

**Comment by nanawel** [comment]
That's perfectly understandable. My mistake.
I'll bump dependencies asap and push a new release.

Thanks for your response.
