### ISSUE TITLE
n8n does not appear in the list

### ISSUE THREAD

**Issue by roener** [awesome-selfhosted/awesome-selfhosted-data#887]
I'm not sure, but it looks like a bug.
An entry for n8n exists (https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/software/n8n.yml), but does not appear in either list (https://awesome-selfhosted.net and https://github.com/awesome-selfhosted/awesome-selfhosted).

Or am I missing something?

**Comment by PmPPolska** [comment]
pt., 11 paź 2024, 13:17 użytkownik roener ***@***.***>
napisał:

**Comment by Rabenherz112** [comment]
Hey there, Since n8n includes the "Commons Clause" license, it's considered non-free software. A "non-free" license restricts how the software can be used.

Because of these limitations, n8n is listed in the [non-free section](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/non-free.md#automation).

**Comment by roener** [comment]
Thanks for the detailed explanation, much appreciated.
Based on this, I consider the issue resolved.
